In [3]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [10]:
observations = 1000

In [11]:
xs = np.random.uniform(low=-10,high=10,size=(observations,1))

In [12]:
xz = np.random.uniform(-10,10,(observations,1))

In [13]:
inputs = np.column_stack((xs,xz))

In [14]:
inputs

array([[-1.55626321,  7.99398996],
       [ 6.04639724,  4.4070749 ],
       [-6.23244276, -2.16919393],
       ...,
       [-0.11282452,  0.44780607],
       [ 6.7729283 , -2.49324881],
       [ 9.78557445, -6.57633739]])

In [17]:
noise = np.random.uniform(-1,1,(observations,1))

In [18]:
noise

array([[-6.58338220e-01],
       [-6.43469170e-01],
       [ 6.28652673e-01],
       [-2.20977133e-01],
       [ 4.22634732e-01],
       [-4.56362006e-01],
       [ 1.17702005e-01],
       [ 9.49153463e-01],
       [ 8.97231971e-01],
       [-1.28040254e-01],
       [ 4.40204917e-02],
       [ 2.13638294e-01],
       [ 1.06283589e-01],
       [ 9.94898098e-01],
       [ 4.88629336e-01],
       [ 7.76103358e-01],
       [ 5.23841562e-02],
       [-8.98403691e-01],
       [-1.94986253e-01],
       [ 6.83258705e-01],
       [ 4.30620507e-01],
       [ 1.55571421e-01],
       [-3.03236872e-01],
       [-7.09272089e-01],
       [-6.13172337e-01],
       [ 3.06921935e-01],
       [-6.90743902e-01],
       [ 8.14017543e-01],
       [ 7.08483979e-01],
       [-8.63156614e-01],
       [ 3.04465530e-01],
       [-1.15207303e-01],
       [-9.38386244e-02],
       [-5.07383410e-01],
       [ 8.30772205e-01],
       [-5.70211564e-01],
       [ 7.02345280e-01],
       [-7.22256422e-01],
       [ 9.5

In [19]:
targets = 2*xs - 3*xz + 5 + noise

In [20]:
targets

array([[-2.27528345e+01],
       [ 3.22810061e+00],
       [-3.28651065e-01],
       [ 1.03730947e+01],
       [-1.07948336e+01],
       [ 4.27437443e+00],
       [ 4.37664611e+01],
       [ 5.15058608e+00],
       [-2.77757672e+01],
       [ 2.63067221e+01],
       [ 4.72107455e+01],
       [ 2.41904445e+01],
       [ 6.80444732e+00],
       [ 3.30424181e+01],
       [ 2.40094714e+01],
       [-1.72355218e+01],
       [ 2.78481639e+01],
       [ 2.63348605e+01],
       [-1.59724381e+01],
       [ 2.16548972e+01],
       [-4.82690917e+00],
       [-9.42287217e-01],
       [-1.76374929e+01],
       [ 3.91080316e+01],
       [ 1.75229813e+01],
       [ 2.43574527e+01],
       [ 2.83526381e+01],
       [-3.40925283e+01],
       [ 1.58251857e+01],
       [ 1.17729343e+01],
       [-2.67893454e+01],
       [-1.97360384e+01],
       [ 5.98673551e-01],
       [-2.89922229e+01],
       [ 4.48211077e+00],
       [ 2.75701717e+00],
       [ 4.26117801e+01],
       [ 2.19284595e+01],
       [-1.4

In [21]:
np.savez('tf_dataset',inputs=inputs,output=targets)

In [22]:
training_data = np.load('tf_dataset.npz')

In [25]:
input_size = 2
output_size =1

In [33]:
model = tf.keras.Sequential([
                        tf.keras.layers.Dense(output_size,
                                             kernel_initializer=tf.random_uniform_initializer(minval=-0.1, maxval=0.1),
                                                 bias_initializer=tf.random_uniform_initializer(minval=-0.1, maxval=0.1)
                                             )
])

In [34]:
custom_optimizer = tf.keras.optimizers.SGD(learning_rate=0.02)
model.compile(optimizer=custom_optimizer,loss='mean_squared_error')

In [35]:
model.fit(x=training_data['inputs'],y=training_data['output'],epochs=100)

Epoch 1/100
32/32 [==============================] - 0s 1ms/step - loss: 24.1496
Epoch 2/100
32/32 [==============================] - 0s 1ms/step - loss: 1.1358
Epoch 3/100
32/32 [==============================] - 0s 1ms/step - loss: 0.4230
Epoch 4/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3745
Epoch 5/100
32/32 [==============================] - 0s 2ms/step - loss: 0.3695
Epoch 6/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3621
Epoch 7/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3601
Epoch 8/100
32/32 [==============================] - 0s 998us/step - loss: 0.3647
Epoch 9/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3780
Epoch 10/100
32/32 [==============================] - 0s 3ms/step - loss: 0.4005
Epoch 11/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3651
Epoch 12/100
32/32 [==============================] - 0s 1ms/step - loss: 0.3816
Epoch 13/100
32/32 [==============

In [36]:
model.layers[0].get_weights()

[array([[ 2.0635989],
        [-3.0453482]], dtype=float32),
 array([5.012521], dtype=float32)]

In [37]:
model.predict_on_batch(training_data['inputs']).round(1)

array([[-22.5],
       [  4.1],
       [ -1.2],
       [ 10.5],
       [-11.4],
       [  4.8],
       [ 44.5],
       [  3.9],
       [-29.2],
       [ 26.6],
       [ 48.1],
       [ 24.3],
       [  6.4],
       [ 32.6],
       [ 24.1],
       [-18.4],
       [ 28.2],
       [ 27.6],
       [-16.1],
       [ 21.1],
       [ -5.2],
       [ -1.1],
       [-17.8],
       [ 40.6],
       [ 18.2],
       [ 24.2],
       [ 29.5],
       [-35.7],
       [ 15.3],
       [ 12.5],
       [-27.8],
       [-20.2],
       [  0.6],
       [-29.2],
       [  3.4],
       [  3.6],
       [ 42.7],
       [ 23.3],
       [ -2.4],
       [ 15. ],
       [-37.5],
       [  5.4],
       [-31.2],
       [-11.1],
       [  6.7],
       [ 26. ],
       [  9.9],
       [ 46. ],
       [ 13.2],
       [-37.7],
       [-23.6],
       [  8.4],
       [-33. ],
       [ 47.5],
       [  2.5],
       [  1.2],
       [ -2.4],
       [-36.7],
       [ -3.8],
       [ 37. ],
       [-26.5],
       [ -9.2],
       [